# NHANES_Mental_Health_Project_Data_Cleaning

In [84]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime

In [85]:
pd.set_option('display.max.columns', 100)

In [86]:
#import the data files
demo = pd.read_sas(r"C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\raw_data\DEMO_L.xpt", encoding='utf-8')
dpq = pd.read_sas(r"C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\raw_data\DPQ_L.xpt", encoding='utf-8')
bmx = pd.read_sas(r"C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\raw_data\BMX_L.xpt", encoding='utf-8')
slq = pd.read_sas(r"C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\raw_data\SLQ_L.xpt", encoding='utf-8')
paq = pd.read_sas(r"C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\raw_data\PAQ_L.xpt", encoding='utf-8')

## Get the Summary of the Data

In [87]:
#make an empty dataframe
column_names = ['File', 'Columns', 'Rows/SEQN Count', 'Duplicate SEQN', 'Missing %']
data_info =pd.DataFrame(columns = column_names)

In [88]:
# fill the empty dataframe
dfs = {'DEMO': demo, 'DPQ': dpq, 'BMX': bmx, 'PAQ': paq, 'SLQ': slq}

summary_list = []
for i, df in dfs.items():
    summary_list.append({
        'File': i,
        'Columns': df.shape[1],
        'Rows/SEQN Count': len(df),
        'Duplicate SEQN': df['SEQN'].duplicated().sum() if 'SEQN' in df else 0,
        'Missing %': round(df.isna().mean().mean() * 100, 2)
    })

data_info = pd.DataFrame(summary_list)

In [89]:
data_info

   File  Columns  Rows/SEQN Count  Duplicate SEQN  Missing %
0  DEMO       27            11933               0      30.97
1   DPQ       11             6337               0      13.76
2   BMX       22             8860               0      54.91
3   PAQ        8             8153               0       9.62
4   SLQ        7             8501               0       0.38

In [90]:
#export the summary data

data_info.to_csv(r'C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\raw_data\data_info.csv')

## Cleaning/Analyzing Demographic Data

In [91]:
demo = demo.round(0)
demo

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,DMDMARTZ,RIDEXPRG,DMDHHSIZ,DMDHRGND,DMDHRAGZ,DMDHREDZ,DMDHRMAZ,DMDHSEDZ,WTINT2YR,WTMEC2YR,SDMVSTRA,SDMVPSU,INDFMPIR
0,130378.0,12.0,2.0,1.0,43.0,NaN,5.0,6.0,2.0,NaN,2.0,2.0,6.0,5.0,1.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,50055.0,54374.0,173.0,2.0,5.0
1,130379.0,12.0,2.0,1.0,66.0,NaN,3.0,3.0,2.0,NaN,2.0,1.0,NaN,5.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,29087.0,34085.0,173.0,2.0,5.0
2,130380.0,12.0,2.0,2.0,44.0,NaN,2.0,2.0,1.0,NaN,2.0,2.0,6.0,3.0,1.0,2.0,7.0,NaN,NaN,NaN,NaN,NaN,80063.0,81196.0,174.0,1.0,1.0
3,130381.0,12.0,2.0,2.0,5.0,NaN,5.0,7.0,1.0,71.0,NaN,1.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,3.0,NaN,38807.0,55699.0,182.0,2.0,2.0
4,130382.0,12.0,2.0,1.0,2.0,NaN,3.0,3.0,2.0,34.0,NaN,1.0,NaN,NaN,NaN,NaN,4.0,2.0,2.0,3.0,1.0,2.0,30608.0,36434.0,182.0,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11928,142306.0,12.0,2.0,1.0,9.0,NaN,2.0,2.0,1.0,111.0,NaN,1.0,NaN,NaN,NaN,NaN,2.0,1.0,3.0,3.0,3.0,NaN,11147.0,13459.0,176.0,1.0,2.0
11929,142307.0,12.0,2.0,2.0,49.0,NaN,4.0,4.0,2.0,NaN,2.0,1.0,NaN,5.0,3.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,69420.0,64962.0,181.0,1.0,NaN
11930,142308.0,12.0,2.0,1.0,50.0,NaN,2.0,2.0,1.0,NaN,2.0,2.0,6.0,4.0,1.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,32696.0,44368.0,183.0,2.0,2.0
11931,142309.0,12.0,2.0,1.0,40.0,NaN,2.0,2.0,1.0,NaN,1.0,1.0,NaN,4.0,2.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,30548.0,46249.0,176.0,1.0,3.0
11932,142310.0,12.0,2.0,2.0,80.0,NaN,3.0,3.0,1.0,NaN,2.0,1.0,NaN,3.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,32754.0,49647.0,187.0,2.0,5.0

In [92]:
demo.describe()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,DMDMARTZ,RIDEXPRG,DMDHHSIZ,DMDHRGND,DMDHRAGZ,DMDHREDZ,DMDHRMAZ,DMDHSEDZ,WTINT2YR,WTMEC2YR,SDMVSTRA,SDMVPSU,INDFMPIR
count,11933.000000,11933.0,11933.000000,11933.000000,11933.000000,377.000000,11933.000000,11933.000000,8860.000000,2787.000000,8301.000000,11914.000000,1875.000000,7794.000000,7792.000000,1503.000000,11933.000000,4115.000000,4124.000000,3746.000000,4020.000000,2127.000000,11933.000000,11933.000000,11933.000000,11933.000000,9892.000000
mean,136344.000000,12.0,1.742479,1.532808,38.317858,11.628647,3.104584,3.320540,1.520203,121.908504,1.916998,1.157378,7.334933,3.804978,1.778491,2.236860,3.242772,1.564277,2.539525,2.171383,1.381095,2.275035,27404.133747,27404.136764,179.918294,1.491746,2.705014
std,3444.904716,0.0,0.437287,0.498943,25.601990,6.805429,1.076346,1.518379,0.499620,67.158655,0.282376,0.364172,15.829158,1.153750,3.101080,0.485254,1.699512,0.495912,0.641094,0.660132,0.681421,0.694050,19449.157074,27962.966090,4.309624,0.499953,1.687951
min,130378.000000,12.0,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4584.000000,0.000000,173.000000,1.000000,0.000000
25%,133361.000000,12.0,1.000000,1.000000,13.000000,6.000000,3.000000,3.000000,1.000000,66.000000,2.000000,1.000000,3.000000,3.000000,1.000000,2.000000,2.000000,1.000000,2.000000,2.000000,1.000000,2.000000,14332.000000,0.000000,176.000000,1.000000,1.000000
50%,136344.000000,12.0,2.000000,2.000000,37.000000,11.000000,3.000000,3.000000,2.000000,122.000000,2.000000,1.000000,6.000000,4.000000,1.000000,2.000000,3.000000,2.000000,2.000000,2.000000,1.000000,2.000000,21670.000000,21718.000000,180.000000,1.000000,2.000000
75%,139327.000000,12.0,2.000000,2.000000,62.000000,17.000000,4.000000,4.000000,2.000000,179.500000,2.000000,1.000000,6.000000,5.000000,2.000000,3.000000,4.000000,2.000000,3.000000,3.000000,2.000000,3.000000,33831.000000,38341.000000,184.000000,2.000000,4.000000
max,142310.000000,12.0,2.000000,2.000000,80.000000,24.000000,5.000000,7.000000,2.000000,239.000000,7.000000,2.000000,99.000000,9.000000,99.000000,3.000000,7.000000,2.000000,4.000000,3.000000,3.000000,3.000000,170968.000000,227108.000000,187.000000,2.000000,5.000000

In [93]:
demo.nunique()

SEQN        11933
SDDSRVYR        1
RIDSTATR        2
RIAGENDR        2
RIDAGEYR       81
RIDAGEMN       25
RIDRETH1        5
RIDRETH3        6
RIDEXMON        2
RIDEXAGM      240
DMQMILIZ        3
DMDBORN4        2
DMDYRUSR        8
DMDEDUC2        6
DMDMARTZ        5
RIDEXPRG        3
DMDHHSIZ        7
DMDHRGND        2
DMDHRAGZ        4
DMDHREDZ        3
DMDHRMAZ        3
DMDHSEDZ        3
WTINT2YR     8829
WTMEC2YR     7590
SDMVSTRA       15
SDMVPSU         2
INDFMPIR        6
dtype: int64

In [94]:
# replace all missing values with nan

demo['DMQMILIZ'] = demo['DMQMILIZ'].replace([7, 9], np.nan)
demo['DMDBORN4'] = demo['DMDBORN4'].replace([77, 99], np.nan)
demo['DMDYRUSR'] = demo['DMDYRUSR'].replace([77, 99], np.nan)
demo['DMDEDUC2'] = demo['DMDEDUC2'].replace([7, 9], np.nan)
demo['DMDMARTZ'] = demo['DMDMARTZ'].replace([77, 99], np.nan)
demo['RIDEXPRG'] = demo['RIDEXPRG'].replace(3, np.nan)

In [95]:
#drop ages younger than 18

demo = demo[demo['RIDAGEYR'] >= 18]

In [96]:
#drop all the non-useful columns

demo = demo.drop(columns = ['SDDSRVYR', 'RIDAGEMN', 
                 'RIDRETH1', 'RIDEXMON', 'RIDEXAGM', 'DMDHRGND', 
                 'DMDHRAGZ', 'DMDHREDZ', 'DMDHRMAZ', 'DMDHSEDZ'])

In [97]:
#drop all empty rows

demo.columns
demo_col = ['RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDRETH3', 'DMQMILIZ', 'DMDBORN4',
       'DMDYRUSR', 'DMDEDUC2', 'DMDMARTZ', 'RIDEXPRG', 'DMDHHSIZ', 'SDMVSTRA',
       'SDMVPSU', 'INDFMPIR']
demo = demo.dropna(how = 'all', subset = demo_col)

### Assign categories to the variables

In [98]:
# Gender

demo['RIAGENDR'] = demo['RIAGENDR'].replace(1, 'Male')
demo['RIAGENDR'] = demo['RIAGENDR'].replace(2, 'Female')

In [99]:
#Race

demo['RIDRETH3'] = demo['RIDRETH3'].replace(1, 'Mexican American')
demo['RIDRETH3'] = demo['RIDRETH3'].replace(2, 'Other Hispanic')
demo['RIDRETH3'] = demo['RIDRETH3'].replace(3, 'White/ Non Hispanic')
demo['RIDRETH3'] = demo['RIDRETH3'].replace(4, 'Black/ Non Hispanic')
demo['RIDRETH3'] = demo['RIDRETH3'].replace(6, 'Asian/ Non Hispanic')
demo['RIDRETH3'] = demo['RIDRETH3'].replace(7, 'Other Race/Multiracial')

In [100]:
# Served in the US Armed Force

demo['DMQMILIZ'] = demo['DMQMILIZ'].replace(1, 'Yes')
demo['DMQMILIZ'] = demo['DMQMILIZ'].replace(2, 'No')

In [101]:
# Born in the US 

demo['DMQMILIZ'] = demo['DMQMILIZ'].replace(1, 'USA')
demo['DMQMILIZ'] = demo['DMQMILIZ'].replace(2, 'Other')

In [102]:
#Length of time in the US

demo['DMDYRUSR'] = demo['DMDYRUSR'].replace(1, '< 1 year')
demo['DMDYRUSR'] = demo['DMDYRUSR'].replace(2, '1 to 4 years')
demo['DMDYRUSR'] = demo['DMDYRUSR'].replace(3, '5 to 9 years')
demo['DMDYRUSR'] = demo['DMDYRUSR'].replace(4, '10 to 14 years')
demo['DMDYRUSR'] = demo['DMDYRUSR'].replace(5, '15 to 19 years')
demo['DMDYRUSR'] = demo['DMDYRUSR'].replace(6, '20 years+')

In [103]:
#Education Level

demo['DMDEDUC2'] = demo['DMDEDUC2'].replace([1, 2], 'Less than high school')
demo['DMDEDUC2'] = demo['DMDEDUC2'].replace(3, 'High school/GED')
demo['DMDEDUC2'] = demo['DMDEDUC2'].replace(4, 'Some college/AA degree')
demo['DMDEDUC2'] = demo['DMDEDUC2'].replace(5, 'College graduate+')

In [104]:
#Marital Status

demo['DMDMARTZ'] = demo['DMDMARTZ'].replace(1, 'Married/Living with partner')
demo['DMDMARTZ'] = demo['DMDMARTZ'].replace(2, 'Widowed/Divorced/Separated')
demo['DMDMARTZ'] = demo['DMDMARTZ'].replace(3, 'Never married')

In [105]:
# Pregnancy Status

demo['RIDEXPRG'] = demo['RIDEXPRG'].replace(1, 'Pregnant')
demo['RIDEXPRG'] = demo['RIDEXPRG'].replace(2, 'Not pregnant')

In [106]:
# Create age group category

age_bins = [18, 35, 50, 65, np.inf]
age_labels = ['18-34', '35-49', '50-64', '65+']

# Create the age group category column
demo['AGE_GROUP'] = pd.cut(demo['RIDAGEYR'], bins=age_bins, labels=age_labels, right=False)

In [107]:
demo

,SEQN,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH3,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,DMDMARTZ,RIDEXPRG,DMDHHSIZ,WTINT2YR,WTMEC2YR,SDMVSTRA,SDMVPSU,INDFMPIR,AGE_GROUP
0,130378.0,2.0,Male,43.0,Asian/ Non Hispanic,No,2.0,20 years+,College graduate+,Married/Living with partner,NaN,4.0,50055.0,54374.0,173.0,2.0,5.0,35-49
1,130379.0,2.0,Male,66.0,White/ Non Hispanic,No,1.0,NaN,College graduate+,Married/Living with partner,NaN,2.0,29087.0,34085.0,173.0,2.0,5.0,65+
2,130380.0,2.0,Female,44.0,Other Hispanic,No,2.0,20 years+,High school/GED,Married/Living with partner,Not pregnant,7.0,80063.0,81196.0,174.0,1.0,1.0,35-49
6,130384.0,1.0,Male,43.0,Mexican American,No,2.0,15 to 19 years,Less than high school,Never married,NaN,2.0,15079.0,0.0,179.0,2.0,1.0,35-49
7,130385.0,1.0,Female,65.0,White/ Non Hispanic,No,1.0,NaN,High school/GED,Married/Living with partner,NaN,2.0,16151.0,0.0,187.0,2.0,5.0,65+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11927,142305.0,2.0,Female,76.0,Mexican American,No,2.0,10 to 14 years,Less than high school,Widowed/Divorced/Separated,NaN,4.0,28980.0,43483.0,180.0,2.0,2.0,65+
11929,142307.0,2.0,Female,49.0,Black/ Non Hispanic,No,1.0,NaN,College graduate+,Never married,NaN,5.0,69420.0,64962.0,181.0,1.0,NaN,35-49
11930,142308.0,2.0,Male,50.0,Other Hispanic,No,2.0,20 years+,Some college/AA degree,Married/Living with partner,NaN,3.0,32696.0,44368.0,183.0,2.0,2.0,50-64
11931,142309.0,2.0,Male,40.0,Other Hispanic,Yes,1.0,NaN,Some college/AA degree,Widowed/Divorced/Separated,NaN,5.0,30548.0,46249.0,176.0,1.0,3.0,35-49
11932,142310.0,2.0,Female,80.0,White/ Non Hispanic,No,1.0,NaN,High school/GED,Married/Living with partner,NaN,2.0,32754.0,49647.0,187.0,2.0,5.0,65+

## Cleaning/Analyzing Depresssion Scale Data

In [108]:
dpq = dpq.round(0)
dpq

,SEQN,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,DPQ100
0,130378.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,130379.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,130380.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,130386.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,130387.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
6332,142305.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6333,142307.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
6334,142308.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
6335,142309.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
6336,142310.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [109]:
#drop all empty rows

dpq_cols = ['DPQ010', 'DPQ020', 'DPQ030', 'DPQ040', 'DPQ050', 'DPQ060', 'DPQ070', 'DPQ080', 'DPQ090']
dpq = dpq.dropna(how = 'all', subset=dpq_cols)

In [110]:
# replace missing 

dpq = dpq.replace([7,9], np.nan)

In [111]:
#create a total category

# Count how many valid answers each person provided
valid = dpq[dpq_cols].notna().sum(axis=1)

# Calculate mean per item and scale back to a 9-item total if at least 7 items were answered
mean_score = dpq[dpq_cols].mean(axis=1)
dpq['DPQ_TOTAL'] = np.where(valid >= 7, mean_score * 9, np.nan)

In [112]:
dpq[dpq['DPQ_TOTAL'] == 9]

,SEQN,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,DPQ100,DPQ_TOTAL
28,130418.0,1.0,1.0,2.0,3.0,0.0,2.0,0.0,0.0,0.0,1.0,9.0
48,130453.0,3.0,1.0,2.0,1.0,0.0,1.0,1.0,0.0,0.0,2.0,9.0
99,130563.0,1.0,2.0,3.0,0.0,0.0,1.0,0.0,0.0,2.0,1.0,9.0
121,130599.0,2.0,1.0,3.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,9.0
152,130656.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6152,141941.0,0.0,0.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,9.0
6166,141971.0,1.0,1.0,2.0,1.0,0.0,1.0,2.0,0.0,1.0,0.0,9.0
6198,142034.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,9.0
6206,142048.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0.0,1.0,9.0
6257,142171.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,0.0,0.0,1.0,9.0

In [113]:
#create category bins

dpq_bins = [-1, 4, 9, 14, 19, 27]
dpq_labels = ['Minimal', 'Mild', 'Moderate', 'Moderately severe', 'Severe']

dpq['DPQ_SEVERITY'] = pd.cut(dpq['DPQ_TOTAL'], bins=dpq_bins, labels=dpq_labels, right=True)

In [114]:
# categorise all data values

dpq[dpq_cols] = dpq[dpq_cols].replace(0, 'Not at all')
dpq[dpq_cols] = dpq[dpq_cols].replace(1, 'Several days')
dpq[dpq_cols] = dpq[dpq_cols].replace(2, 'More than half the days')
dpq[dpq_cols] = dpq[dpq_cols].replace(3, 'Nearly every day')

In [115]:
# categorise DPQ100, put NaN as 'Not difficult at all

dpq['DPQ100'] = dpq['DPQ100'].replace(0, 'Not difficult at all')
dpq['DPQ100'] = dpq['DPQ100'].replace(1, 'Somewhat difficult')
dpq['DPQ100'] = dpq['DPQ100'].replace(2, 'Very difficult')
dpq['DPQ100'] = dpq['DPQ100'].replace(3, 'Extremely difficult')
dpq['DPQ100'] = dpq['DPQ100'].replace(np.nan, 'Not difficult at all')

In [116]:
dpq

,SEQN,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,DPQ100,DPQ_TOTAL,DPQ_SEVERITY
1,130379.0,Not at all,Not at all,Several days,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,1.0,Minimal
2,130380.0,Not at all,Not at all,Several days,Several days,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,2.0,Minimal
3,130386.0,Not at all,Not at all,Not at all,Not at all,Not at all,Several days,Not at all,Not at all,Not at all,Not difficult at all,1.0,Minimal
4,130387.0,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,0.0,Minimal
6,130389.0,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,0.0,Minimal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6331,142303.0,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,0.0,Minimal
6333,142307.0,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,0.0,Minimal
6334,142308.0,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,0.0,Minimal
6335,142309.0,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,0.0,Minimal
6336,142310.0,Not at all,Not at all,Not at all,Several days,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,1.0,Minimal

## Cleaning/Analyzing Body Measurement Data

In [117]:
bmx1 = bmx

In [118]:
bmx1

,SEQN,BMDSTATS,BMXWT,BMIWT,BMXRECUM,BMIRECUM,BMXHEAD,BMIHEAD,BMXHT,BMIHT,BMXBMI,BMDBMIC,BMXLEG,BMILEG,BMXARML,BMIARML,BMXARMC,BMIARMC,BMXWAIST,BMIWAIST,BMXHIP,BMIHIP
0,130378.0,1.0,86.9,NaN,NaN,NaN,NaN,NaN,179.5,NaN,27.0,NaN,42.8,NaN,42.0,NaN,35.7,NaN,98.3,NaN,102.9,NaN
1,130379.0,1.0,101.8,NaN,NaN,NaN,NaN,NaN,174.2,NaN,33.5,NaN,38.5,NaN,38.7,NaN,33.7,NaN,114.7,NaN,112.4,NaN
2,130380.0,1.0,69.4,NaN,NaN,NaN,NaN,NaN,152.9,NaN,29.7,NaN,38.5,NaN,35.5,NaN,36.3,NaN,93.5,NaN,98.0,NaN
3,130381.0,1.0,34.3,NaN,NaN,NaN,NaN,NaN,120.1,NaN,23.8,4.0,NaN,NaN,25.4,NaN,23.4,NaN,70.4,NaN,NaN,NaN
4,130382.0,3.0,13.6,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8855,142306.0,1.0,25.3,NaN,NaN,NaN,NaN,NaN,128.0,NaN,15.4,2.0,32.0,NaN,25.0,NaN,19.0,NaN,57.7,NaN,NaN,NaN
8856,142307.0,3.0,NaN,1.0,NaN,NaN,NaN,NaN,143.8,NaN,NaN,NaN,NaN,1.0,34.0,NaN,35.4,NaN,NaN,1.0,NaN,1.0
8857,142308.0,1.0,79.3,NaN,NaN,NaN,NaN,NaN,173.3,NaN,26.4,NaN,41.8,NaN,40.0,NaN,30.6,NaN,98.4,NaN,97.7,NaN
8858,142309.0,1.0,81.9,NaN,NaN,NaN,NaN,NaN,179.1,NaN,25.5,NaN,44.0,NaN,40.0,NaN,30.8,NaN,96.0,NaN,103.3,NaN
8859,142310.0,1.0,72.1,NaN,NaN,NaN,NaN,NaN,161.7,NaN,27.6,NaN,34.2,NaN,34.0,NaN,33.5,NaN,110.8,NaN,115.0,NaN

In [119]:
# drop the columns without measurement

bmx1 = bmx1.drop(bmx1[bmx1['BMDSTATS'] == 4].index)

In [120]:
bmx1['BMXBMI'].max()

74.8

In [121]:
bmx1[bmx1['BMXBMI'] > 60]

,SEQN,BMDSTATS,BMXWT,BMIWT,BMXRECUM,BMIRECUM,BMXHEAD,BMIHEAD,BMXHT,BMIHT,BMXBMI,BMDBMIC,BMXLEG,BMILEG,BMXARML,BMIARML,BMXARMC,BMIARMC,BMXWAIST,BMIWAIST,BMXHIP,BMIHIP
493,131019.0,2.0,155.4,NaN,NaN,NaN,NaN,NaN,152.9,NaN,66.5,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0
683,131299.0,3.0,186.4,NaN,NaN,NaN,NaN,NaN,175.4,NaN,60.6,NaN,NaN,1.0,41.1,NaN,51.1,NaN,164.6,NaN,176.7,NaN
1225,132014.0,3.0,179.5,NaN,NaN,NaN,NaN,NaN,160.2,NaN,69.9,NaN,NaN,1.0,NaN,1.0,NaN,1.0,169.0,NaN,176.2,NaN
2521,133741.0,1.0,167.9,NaN,NaN,NaN,NaN,NaN,162.0,NaN,64.0,NaN,42.6,NaN,40.0,NaN,51.4,NaN,133.1,NaN,171.1,NaN
2954,134348.0,1.0,192.1,NaN,NaN,NaN,NaN,NaN,167.5,3.0,68.5,NaN,39.5,NaN,40.0,NaN,51.0,NaN,170.0,NaN,187.1,NaN
3003,134413.0,1.0,248.2,NaN,NaN,NaN,NaN,NaN,189.8,NaN,68.9,NaN,41.8,NaN,49.1,NaN,54.5,NaN,187.0,NaN,180.4,NaN
3245,134736.0,3.0,156.7,NaN,NaN,NaN,NaN,NaN,159.6,NaN,61.5,NaN,NaN,1.0,34.1,NaN,51.5,NaN,148.3,NaN,159.1,NaN
3384,134940.0,3.0,184.2,NaN,NaN,NaN,NaN,NaN,165.7,NaN,67.1,NaN,NaN,1.0,39.5,NaN,47.6,NaN,151.8,NaN,180.0,NaN
3614,135246.0,3.0,222.7,NaN,NaN,NaN,NaN,NaN,179.5,NaN,69.1,NaN,NaN,1.0,40.0,NaN,61.0,NaN,NaN,1.0,NaN,1.0
3718,135397.0,3.0,163.4,NaN,NaN,NaN,NaN,NaN,158.9,NaN,64.7,NaN,NaN,1.0,36.5,NaN,47.1,NaN,NaN,1.0,NaN,1.0
3894,135637.0,2.0,185.2,3.0,NaN,NaN,NaN,NaN,157.3,NaN,74.8,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0
4341,136251.0,3.0,161.9,NaN,NaN,NaN,NaN,NaN,155.9,NaN,66.6,4.0,NaN,1.0,33.0,NaN,48.7,NaN,NaN,1.0,163.6,NaN
4380,136302.0,1.0,162.4,NaN,NaN,NaN,NaN,NaN,160.1,NaN,63.4,NaN,37.7,NaN,43.0,NaN,63.3,NaN,149.4,NaN,166.6,NaN
4605,136609.0,1.0,148.8,NaN,NaN,NaN,NaN,NaN,155.6,NaN,61.5,NaN,37.4,NaN,39.5,NaN,52.8,NaN,140.9,NaN,156.8,NaN
4810,136883.0,1.0,160.5,NaN,NaN,NaN,NaN,NaN,161.0,NaN,61.9,NaN,37.9,NaN,38.7,NaN,47.2,NaN,158.6,NaN,161.9,NaN
4958,137079.0,1.0,172.9,NaN,NaN,NaN,NaN,NaN,161.7,NaN,66.1,4.0,38.8,NaN,41.8,NaN,51.0,NaN,144.5,NaN,162.0,NaN
5323,137579.0,1.0,166.7,NaN,NaN,NaN,NaN,NaN,159.9,NaN,65.2,NaN,28.4,NaN,39.0,NaN,49.4,NaN,151.2,NaN,181.0,NaN
6788,139533.0,1.0,173.4,NaN,NaN,NaN,NaN,NaN,168.0,NaN,61.4,NaN,37.3,NaN,34.7,NaN,50.3,NaN,151.2,NaN,166.9,NaN
6812,139569.0,1.0,145.2,NaN,NaN,NaN,NaN,NaN,151.8,NaN,63.0,NaN,30.0,NaN,31.0,NaN,50.0,NaN,156.0,NaN,167.7,NaN
7058,139899.0,1.0,202.8,NaN,NaN,NaN,NaN,NaN,182.9,NaN,60.6,NaN,42.5,NaN,42.0,NaN,51.7,NaN,171.5,NaN,170.0,NaN
7120,139981.0,1.0,174.5,NaN,NaN,NaN,NaN,NaN,168.4,NaN,61.5,NaN,35.3,NaN,44.9,NaN,50.1,NaN,156.7,NaN,142.3,NaN
7311,140219.0,1.0,191.5,NaN,NaN,NaN,NaN,NaN,168.1,NaN,67.8,NaN,38.5,NaN,37.2,NaN,56.0,NaN,177.2,NaN,182.5,NaN
7489,140480.0,3.0,224.1,NaN,NaN,NaN,NaN,NaN,191.7,NaN,61.0,NaN,NaN,1.0,42.8,NaN,47.6,NaN,NaN,1.0,NaN,1.0
7557,140570.0,1.0,173.3,NaN,NaN,NaN,NaN,NaN,163.6,NaN,64.7,NaN,36.7,NaN,38.3,NaN,57.8,NaN,165.2,NaN,166.0,NaN
8372,141644.0,1.0,177.9,NaN,NaN,NaN,NaN,NaN,171.5,NaN,60.5,NaN,40.0,NaN,42.5,NaN,55.1,NaN,151.7,NaN,166.5,NaN
8419,141710.0,2.0,146.9,3.0,NaN,NaN,NaN,NaN,152.8,NaN,62.9,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0

In [122]:
# create a manual calculation and compare with CDC's BMI
bmx1['BMI_CALC'] = bmx1['BMXWT'] / ((bmx1['BMXHT'] / 100) ** 2)
bmx1['BMI_CALC'] = bmx1['BMI_CALC'].round(1)

In [123]:
bmx1_nomatch = bmx1[bmx1['BMI_CALC'] != bmx1['BMXBMI']]
bmx1_nomatch.nunique()

#all the values matched

SEQN        320
BMDSTATS      3
BMXWT       116
BMIWT         3
BMXRECUM    178
BMIRECUM      1
BMXHEAD      49
BMIHEAD       0
BMXHT        26
BMIHT         2
BMXBMI        0
BMDBMIC       0
BMXLEG       14
BMILEG        1
BMXARML     107
BMIARML       1
BMXARMC      88
BMIARMC       1
BMXWAIST     25
BMIWAIST      1
BMXHIP       15
BMIHIP        1
BMI_CALC      0
dtype: int64

In [124]:
# create category bins

bmx_bins = [0, 18.5, 25.0, 30.0, 35.0, 40.0, np.inf]
bmx_labels = ['Underweight', 'Healthy Weight', 'Overweight', 'Obesity (Class 1)', 'Obesity (Class 2)', 'Severe Obesity']

bmx1['BMI_CATEGORY'] = pd.cut(bmx1['BMXBMI'], bins=bmx_bins, labels=bmx_labels, right=False)

In [125]:
#drop non-useful columns
bmx1 = bmx1.drop(columns = ['BMIWT', 'BMIRECUM', 'BMIHEAD',
                          'BMIHT', 'BMILEG', 'BMIARML',
                          'BMIARMC', 'BMIWAIST', 'BMIHIP'])

In [126]:
bmx = bmx1
bmx

,SEQN,BMDSTATS,BMXWT,BMXRECUM,BMXHEAD,BMXHT,BMXBMI,BMDBMIC,BMXLEG,BMXARML,BMXARMC,BMXWAIST,BMXHIP,BMI_CALC,BMI_CATEGORY
0,130378.0,1.0,86.9,NaN,NaN,179.5,27.0,NaN,42.8,42.0,35.7,98.3,102.9,27.0,Overweight
1,130379.0,1.0,101.8,NaN,NaN,174.2,33.5,NaN,38.5,38.7,33.7,114.7,112.4,33.5,Obesity (Class 1)
2,130380.0,1.0,69.4,NaN,NaN,152.9,29.7,NaN,38.5,35.5,36.3,93.5,98.0,29.7,Overweight
3,130381.0,1.0,34.3,NaN,NaN,120.1,23.8,4.0,NaN,25.4,23.4,70.4,NaN,23.8,Healthy Weight
4,130382.0,3.0,13.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8855,142306.0,1.0,25.3,NaN,NaN,128.0,15.4,2.0,32.0,25.0,19.0,57.7,NaN,15.4,Underweight
8856,142307.0,3.0,NaN,NaN,NaN,143.8,NaN,NaN,NaN,34.0,35.4,NaN,NaN,NaN,NaN
8857,142308.0,1.0,79.3,NaN,NaN,173.3,26.4,NaN,41.8,40.0,30.6,98.4,97.7,26.4,Overweight
8858,142309.0,1.0,81.9,NaN,NaN,179.1,25.5,NaN,44.0,40.0,30.8,96.0,103.3,25.5,Overweight
8859,142310.0,1.0,72.1,NaN,NaN,161.7,27.6,NaN,34.2,34.0,33.5,110.8,115.0,27.6,Overweight

## Cleaning/Analyzing Physical Activity Data

In [127]:
paq = paq.round(0)

In [128]:
paq1 = paq

In [129]:
# replace missing 

paq1 = paq1.replace([7777,9999], np.nan)

In [130]:
#drop all empty rows

paq1.columns
paq1_cols =['PAD790Q', 'PAD790U', 'PAD800', 'PAD810Q', 'PAD810U', 'PAD820',
       'PAD680']

paq1= paq1.dropna(how ='all', subset = paq1_cols)

In [131]:
#convert all PAD790Q to weeks
paq1.loc[paq1['PAD790U'] == 'D', 'PAD790Q'] *= 7
paq1.loc[paq1['PAD790U'] == 'M', 'PAD790Q'] /= 4
paq1.loc[paq1['PAD790U'] == 'Y', 'PAD790Q'] /= 52

paq1['PAD790U'] = paq1['PAD790U'].str.replace('D','W')
paq1['PAD790U'] = paq1['PAD790U'].str.replace('M','W')
paq1['PAD790U'] = paq1['PAD790U'].str.replace('Y','W')

In [132]:
#convert all PAD810Q to weeks
paq1.loc[paq1['PAD810U'] == 'D', 'PAD810Q'] *= 7
paq1.loc[paq1['PAD810U'] == 'M', 'PAD810Q'] /= 4
paq1.loc[paq1['PAD810U'] == 'Y', 'PAD810Q'] /= 52

paq1['PAD810U'] = paq1['PAD810U'].str.replace('D','W')
paq1['PAD810U'] = paq1['PAD810U'].str.replace('M','W')
paq1['PAD810U'] = paq1['PAD810U'].str.replace('Y','W')

In [133]:
#convert minutes of moderate, vigorous and sedentary activity to weekly minutes
paq1['PAD_MA/W'] = paq1['PAD800'] * paq1['PAD790Q']
paq1['PAD_VA/W'] = paq1['PAD820'] * paq1['PAD810Q']
paq1['PAD_SA/W'] = paq1['PAD680'] * 7

In [134]:
#fill missing values with 0 for active minutes
paq1['PAD_MA/W'] = paq1['PAD_MA/W'].fillna(0)
paq1['PAD_VA/W'] = paq1['PAD_VA/W'].fillna(0)

In [135]:
#calculate total activity per week, double the PAD_VA/W
paq1['TOTAL_MV/W'] = paq1['PAD_MA/W'] + (paq1['PAD_VA/W'] * 2)

In [136]:
#create category bins
bins = [-1, 150, 300, float('inf')]
labels = ['Low activity', 'Moderate activity', 'High activity']

paq1['PHY_ACTIVITY_CAT'] = pd.cut(paq1['TOTAL_MV/W'], bins=bins, labels=labels)

In [137]:
paq = paq1
paq

,SEQN,PAD790Q,PAD790U,PAD800,PAD810Q,PAD810U,PAD820,PAD680,PAD_MA/W,PAD_VA/W,PAD_SA/W,TOTAL_MV/W,PHY_ACTIVITY_CAT
0,130378.0,3.0,W,45.0,3.0,W,45.0,360.0,135.0,135.0,2520.0,405.0,High activity
1,130379.0,4.0,W,45.0,3.0,W,45.0,480.0,180.0,135.0,3360.0,450.0,High activity
2,130380.0,1.0,W,20.0,0.0,,NaN,240.0,20.0,0.0,1680.0,20.0,Low activity
3,130384.0,0.0,,NaN,0.0,,NaN,60.0,0.0,0.0,420.0,0.0,Low activity
4,130385.0,7.0,W,90.0,1.0,W,60.0,180.0,630.0,60.0,1260.0,750.0,High activity
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8148,142305.0,2.0,W,40.0,0.0,,NaN,480.0,80.0,0.0,3360.0,80.0,Low activity
8149,142307.0,3.0,W,15.0,0.0,,NaN,480.0,45.0,0.0,3360.0,45.0,Low activity
8150,142308.0,1.0,W,45.0,0.0,,NaN,600.0,45.0,0.0,4200.0,45.0,Low activity
8151,142309.0,14.0,W,15.0,0.0,,NaN,240.0,210.0,0.0,1680.0,210.0,Moderate activity
8152,142310.0,0.0,,NaN,0.0,,NaN,360.0,0.0,0.0,2520.0,0.0,Low activity

## Cleaning/Analyzing Sleep Data

In [138]:
slq1 = slq

In [139]:
# replace missing 

slq1 = slq1.replace([7777,9999], np.nan)

In [140]:
# drop all empty columns

slq1.columns
slq1_cols = ['SLQ300', 'SLQ310', 'SLD012', 'SLQ320', 'SLQ330', 'SLD013']

slq1 = slq1.dropna(how = 'all', subset= slq1_cols)

In [141]:
# find the average sleep time
slq1['SLQ_AVERAGE'] = (slq1['SLD012'] + slq1['SLD013']) / 2

In [142]:
# create a sleep time category

slq_bins = [0, 3, 5, 7, 9, 14, np.inf]
slq_labels = ['Less than 3 hours', '3-5 hours', '5-7 hours', '7-9 hours', '9-14 hours', '14 or more hours']

# Create sleep time category for weekdays
slq1['SLQ_CATEGORY_WD'] = pd.cut(slq1['SLD012'], bins=slq_bins, labels=slq_labels, right=False)

# Create sleep time category for weekends
slq1['SLQ_CATEGORY_WE'] = pd.cut(slq1['SLD013'], bins=slq_bins, labels=slq_labels, right=False)

# Create sleep time category for slq_average
slq1['SLQ_CATEGORY_AVG'] = pd.cut(slq1['SLQ_AVERAGE'], bins=slq_bins, labels=slq_labels, right=False)

In [143]:
slq1[slq1['SLQ_CATEGORY_WD'] != slq1['SLQ_CATEGORY_WE']]

,SEQN,SLQ300,SLQ310,SLD012,SLQ320,SLQ330,SLD013,SLQ_AVERAGE,SLQ_CATEGORY_WD,SLQ_CATEGORY_WE,SLQ_CATEGORY_AVG
2,130380.0,00:00,08:00,8.0,00:00,09:00,9.0,8.50,7-9 hours,9-14 hours,7-9 hours
6,130387.0,04:00,07:00,3.0,03:00,08:00,5.0,4.00,3-5 hours,5-7 hours,3-5 hours
15,130396.0,22:00,06:30,8.5,22:00,07:00,9.0,8.75,7-9 hours,9-14 hours,7-9 hours
17,130398.0,06:30,12:00,5.5,07:00,11:00,4.0,4.75,5-7 hours,3-5 hours,3-5 hours
19,130400.0,22:00,07:30,9.5,03:00,11:00,8.0,8.75,9-14 hours,7-9 hours,7-9 hours
...,...,...,...,...,...,...,...,...,...,...,...
8490,142298.0,22:00,05:00,7.0,01:00,05:00,4.0,5.50,7-9 hours,3-5 hours,5-7 hours
8492,142300.0,22:30,07:00,8.5,22:30,08:00,9.5,9.00,7-9 hours,9-14 hours,9-14 hours
8495,142303.0,22:00,06:00,8.0,23:00,09:00,10.0,9.00,7-9 hours,9-14 hours,9-14 hours
8498,142308.0,21:30,06:30,9.0,00:00,08:00,8.0,8.50,9-14 hours,7-9 hours,7-9 hours
8499,142309.0,21:00,05:00,8.0,00:00,12:00,12.0,10.00,7-9 hours,9-14 hours,9-14 hours

In [144]:
slq = slq1

## Get the Summary of the Clean Data

In [145]:
# fill the dataframe
dfs = {'DEMO': demo, 'DPQ': dpq, 'BMX': bmx, 'PAQ': paq, 'SLQ': slq}

summary_list = []
for i, df in dfs.items():
    summary_list.append({
        'File': i,
        'Columns': df.shape[1],
        'Rows/SEQN Count': len(df),
        'Duplicate SEQN': df['SEQN'].duplicated().sum() if 'SEQN' in df else 0,
        'Missing %': round(df.isna().mean().mean() * 100, 2)
    })

cleaned_data_info = pd.DataFrame(summary_list)

In [146]:
cleaned_data_info

   File  Columns  Rows/SEQN Count  Duplicate SEQN  Missing %
0  DEMO       18             8153               0      10.76
1   DPQ       13             5519               0       0.23
2   BMX       15             8791               0      22.12
3   PAQ       13             8153               0       6.19
4   SLQ       11             8501               0       0.79

In [147]:
#export all cleaned data and the summary data

demo.to_csv(r'C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\clean_data\DEMO.csv')
dpq.to_csv(r'C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\clean_data\DPQ.csv')
bmx.to_csv(r'C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\clean_data\BMX.csv')
paq.to_csv(r'C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\clean_data\PAQ.csv')
slq.to_csv(r'C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\clean_data\SLQ.csv')
cleaned_data_info.to_csv(r'C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\clean_data\cleaned_data_info.csv')

# Merge Data

In [148]:
demo1 = demo
dpq1 = dpq
bmx1 = bmx
paq1 = paq
slq1 = slq

In [149]:
new_df = demo1.merge(dpq1, how ='left', on = 'SEQN')

In [150]:
new_df = new_df.merge(bmx1, how ='left', on = 'SEQN')

In [151]:
new_df = new_df.merge(paq1, how ='left', on = 'SEQN')

In [152]:
new_df = new_df.merge(slq1, how ='left', on = 'SEQN')

In [153]:
new_df

,SEQN,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH3,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,DMDMARTZ,RIDEXPRG,DMDHHSIZ,WTINT2YR,WTMEC2YR,SDMVSTRA,SDMVPSU,INDFMPIR,AGE_GROUP,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,DPQ100,DPQ_TOTAL,DPQ_SEVERITY,BMDSTATS,BMXWT,BMXRECUM,BMXHEAD,BMXHT,BMXBMI,BMDBMIC,BMXLEG,BMXARML,BMXARMC,BMXWAIST,BMXHIP,BMI_CALC,BMI_CATEGORY,PAD790Q,PAD790U,PAD800,PAD810Q,PAD810U,PAD820,PAD680,PAD_MA/W,PAD_VA/W,PAD_SA/W,TOTAL_MV/W,PHY_ACTIVITY_CAT,SLQ300,SLQ310,SLD012,SLQ320,SLQ330,SLD013,SLQ_AVERAGE,SLQ_CATEGORY_WD,SLQ_CATEGORY_WE,SLQ_CATEGORY_AVG
0,130378.0,2.0,Male,43.0,Asian/ Non Hispanic,No,2.0,20 years+,College graduate+,Married/Living with partner,NaN,4.0,50055.0,54374.0,173.0,2.0,5.0,35-49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,86.9,NaN,NaN,179.5,27.0,NaN,42.8,42.0,35.7,98.3,102.9,27.0,Overweight,3.0,W,45.0,3.0,W,45.0,360.0,135.0,135.0,2520.0,405.0,High activity,21:30,07:00,9.5,00:00,09:00,9.0,9.25,9-14 hours,9-14 hours,9-14 hours
1,130379.0,2.0,Male,66.0,White/ Non Hispanic,No,1.0,NaN,College graduate+,Married/Living with partner,NaN,2.0,29087.0,34085.0,173.0,2.0,5.0,65+,Not at all,Not at all,Several days,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,1.0,Minimal,1.0,101.8,NaN,NaN,174.2,33.5,NaN,38.5,38.7,33.7,114.7,112.4,33.5,Obesity (Class 1),4.0,W,45.0,3.0,W,45.0,480.0,180.0,135.0,3360.0,450.0,High activity,21:00,06:00,9.0,21:00,06:00,9.0,9.00,9-14 hours,9-14 hours,9-14 hours
2,130380.0,2.0,Female,44.0,Other Hispanic,No,2.0,20 years+,High school/GED,Married/Living with partner,Not pregnant,7.0,80063.0,81196.0,174.0,1.0,1.0,35-49,Not at all,Not at all,Several days,Several days,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,2.0,Minimal,1.0,69.4,NaN,NaN,152.9,29.7,NaN,38.5,35.5,36.3,93.5,98.0,29.7,Overweight,1.0,W,20.0,0.0,,NaN,240.0,20.0,0.0,1680.0,20.0,Low activity,00:00,08:00,8.0,00:00,09:00,9.0,8.50,7-9 hours,9-14 hours,7-9 hours
3,130384.0,1.0,Male,43.0,Mexican American,No,2.0,15 to 19 years,Less than high school,Never married,NaN,2.0,15079.0,0.0,179.0,2.0,1.0,35-49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,,NaN,0.0,,NaN,60.0,0.0,0.0,420.0,0.0,Low activity,21:30,05:00,7.5,23:00,07:00,8.0,7.75,7-9 hours,7-9 hours,7-9 hours
4,130385.0,1.0,Female,65.0,White/ Non Hispanic,No,1.0,NaN,High school/GED,Married/Living with partner,NaN,2.0,16151.0,0.0,187.0,2.0,5.0,65+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,W,90.0,1.0,W,60.0,180.0,630.0,60.0,1260.0,750.0,High activity,22:05,06:15,8.0,22:05,06:15,8.0,8.00,7-9 hours,7-9 hours,7-9 hours
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8148,142305.0,2.0,Female,76.0,Mexican American,No,2.0,10 to 14 years,Less than high school,Widowed/Divorced/Separated,NaN,4.0,28980.0,43483.0,180.0,2.0,2.0,65+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,60.4,NaN,NaN,151.4,26.4,NaN,33.2,32.4,31.2,89.0,96.4,26.4,Overweight,2.0,W,40.0,0.0,,NaN,480.0,80.0,0.0,3360.0,80.0,Low activity,00:00,09:00,9.0,00:00,09:00,9.0,9.00,9-14 hours,9-14 hours,9-14 hours
8149,142307.0,2.0,Female,49.0,Black/ Non Hispanic,No,1.0,NaN,College graduate+,Never married,NaN,5.0,69420.0,64962.0,181.0,1.0,NaN,35-49,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,0.0,Minimal,3.0,NaN,NaN,NaN,143.8,NaN,NaN,NaN,34.0,35.4,NaN,NaN,NaN,NaN,3.0,W,15.0,0.0,,NaN,480.0,45.0,0.0,3360.0,45.0,Low activity,00:00,07:00,7.0,00:00,07:00,7.0,7.00,7-9 hours,7-9 hours,7-9 hours
8150,142308.0,2.0,Male,50.0,Other Hispanic,No,2.0,20 years+,Some college/AA degree,Married/Living with partner,NaN,3.0,32696.0,44368.0,183.0,2.0,2.0,50-64,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,0.0,Minimal,1.0,79.3,NaN,NaN,173.3,26.4,NaN,41.8,40.0,30.6,98.4,97.7,26.4,Overweight,1.0,W,45.0,0.0,,NaN,600.0,45.0,0.0,4200.0,45.0,Low activity,21:30,06:30,9.0,00:00,08:00,8.0,8.50,9-14 hours,7-9 hours,7-9 hours
8151,142309.0,2.0,Male,40.0,Other Hispanic,Yes,1.0,NaN,Some college/AA degree,Widowed/Divorced/Separated,NaN,5.0,30548.0,46249.0,176.0,1.0,3.0,35-49,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,0.0,Minimal,1.0,81.9,NaN,NaN,179.1,25.5,NaN,44.0,40.0,30.8,96.0,103.3,25.5,Overweight,14.0,W,15.0,0.0,,NaN,240.0,210.0,0.0,1680.0,210.0,Moderate activity,21:00,05:00,8.0,00:00,12:00,12.0,10.00,7-9 hours,9-14 hours,9-14 hours
8152,142310.0,2.0,Female,80.0,White/ Non Hispanic,No,1.0,NaN,High school/GED,Married/Living with partner,NaN,2.0,32754.0,49647.0,187.0,2.0,5.0,65+,Not at all,Not at all,Not at all,Several days,Not at all,Not at all,Not at all,Not at all,Not at all,Not difficult at all,1.0,Minimal,1.0,72.1,NaN,NaN,161.7,27.6,NaN,34.2,34.0,33.5,110.8,115.0,27.6,Overweight,0.0,,NaN,0.0,,NaN,360.0,0.0,0.0,2520.0,0.0,Low activity,22:00,07:00,9.0,22:00,07:00,9.0,9.00,9-14 hours,9-14 hours,9-14 hours

In [154]:
round(new_df['DPQ_TOTAL'].isna().mean()* 100, 2)

# about 32.5% of participants do not have a value for PHQ-9

np.float64(32.5)

### Find the missing and valid values percentage

In [157]:
# fill the dataframe

dfs = {'RIAGENDR': new_df['RIAGENDR'], 'RIDAGEYR': new_df['RIDAGEYR'], 'DPQ_TOTAL': new_df['DPQ_TOTAL'], 
       'BMXBMI': new_df['BMXBMI'], 'TOTAL_MV/W': new_df['TOTAL_MV/W'], 
       'PAD_SA/W': new_df['PAD_SA/W'], 'SLQ_CATEGORY_AVG': new_df['SLQ_CATEGORY_AVG']}

dcells = []
for i, j in dfs.items():
    dcells.append({
        'Variable': i,
        'Total Respondents': len(j),
        'Valid count': round(j.count()),
        'Missing count': round(j.isna().sum()),
        'Valid %': round(j.count()/ len(j) * 100, 2),
        'Missing %': round(j.isna().mean().mean() * 100, 2)
        })

variables_info = pd.DataFrame(dcells)
variables_info

,Variable,Total Respondents,Valid count,Missing count,Valid %,Missing %
0,RIAGENDR,8153,8153,0,100.00,0.00
1,RIDAGEYR,8153,8153,0,100.00,0.00
2,DPQ_TOTAL,8153,5503,2650,67.50,32.50
3,BMXBMI,8153,6235,1918,76.47,23.53
4,TOTAL_MV/W,8153,8153,0,100.00,0.00
5,PAD_SA/W,8153,8065,88,98.92,1.08
6,SLQ_CATEGORY_AVG,8153,8011,142,98.26,1.74

In [158]:
#save both files
new_df.to_csv(r'C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\clean_data\merged_data.csv')
variables_info.to_csv(r'C:\Users\amyud\OneDrive\Documents\NHANES_Mental_Health_Project\clean_data\variables_info.csv')